version: '2'

services:
  auth:
    image: httpd:latest
    ports:
      - '8088:80'
      - '10443:443'
    volumes:
      - ./development/auth/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./development/auth/.htaccess:/usr/local/apache2/htdocs/auth/.htaccess
      - ./development/auth/.htpasswd:/usr/local/apache2/htdocs/auth/.htpasswd
      - ./development/auth/index.html:/usr/local/apache2/htdocs/auth/index.html

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'

  moodle:
    image: 'bitnami/moodle:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'moodle_data:/bitnami'
      - ./src/basicauthproxy:/opt/bitnami/moodle/auth/basicauthproxy
      - ./development/moodle/php.ini_dev_only:/opt/bitnami/php/lib/php.ini
    depends_on:
      - mariadb
      - auth

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

